services:
  db:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_campaign_manager
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  web:
    build: .
    depends_on:
      - db
      - elasticsearch
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: 'db'
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      DATABASE_NAME: user_campaign_manager
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    volumes:
      - .:/rails
    command: ./bin/rails server -b 0.0.0.0
    networks:
      - app-network

  frontend:
    image: node:20
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    command: ["sh", "-c", "yarn install && yarn dev --host 0.0.0.0"]
    networks:
      - app-network

volumes:
  db-data:
  es-data:

networks:
  app-network:
    driver: bridge
